openapi: "3.0.0"
info:
    version: 1.0.0
    title: Swagger Petstore
    license:
        name: MIT
servers:
    - url: http://petstore.swagger.io/v1
paths:
    /pets:
        get:
            summary: List all pets
            operationId: listPets
            tags:
                - pets
            parameters:
                - name: limit
                  in: query
                  description: How many items to return at one time (max 100)
                  required: false
                  schema:
                    type: integer
                    maximum: 100
                    format: int32
            responses:
                '200':
                    description: A paged array of pets
                    headers:
                        x-next:
                            description: A link to the next page of responses
                            schema:
                                type: string
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Pets"
                default:
                    description: unexpected error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
            x-codeSamples:
                - lang: go
                  label: listPets
                  source: |-
                    package main

                    import(
                    	petsdk "petsdk/v2"
                    	"context"
                    	"log"
                    )

                    func main() {
                        s := petsdk.New()


                        var limit *int = petsdk.Int(21453)

                        ctx := context.Background()
                        res, err := s.ListPets(ctx, limit)
                        if err != nil {
                            log.Fatal(err)
                        }
                        if res.Pets != nil {
                            // handle response
                        }
                    }
                - lang: typescript
                  label: listPets
                  source: "import { PetSDK } from \"petsdk\";\n\nconst petSDK = new PetSDK();\n\nasync function run() {\n  const limit = 21453;\n  \n  const result = await petSDK.listPets(limit);\n\n  // Handle the result\n  console.log(result)\n}\n\nrun();"
                - lang: python
                  label: listPets
                  source: |-
                    import petsdk

                    s = petsdk.PetSDK()

                    res = s.list_pets(limit=21453)

                    if res.pets is not None:
                        # handle response
                        pass
        post:
            summary: Create a pet
            operationId: createPets
            tags:
                - pets
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Pet'
                required: true
            responses:
                '201':
                    description: Null response
                default:
                    description: unexpected error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
            x-codeSamples:
                - lang: go
                  label: createPets
                  source: |-
                    package main

                    import(
                    	petsdk "petsdk/v2"
                    	"context"
                    	"petsdk/v2/models/components"
                    	"log"
                    )

                    func main() {
                        s := petsdk.New()

                        ctx := context.Background()
                        res, err := s.CreatePets(ctx, components.Pet{
                            ID: 596804,
                            Name: "<value>",
                        })
                        if err != nil {
                            log.Fatal(err)
                        }
                        if res != nil {
                            // handle response
                        }
                    }
                - lang: typescript
                  label: createPets
                  source: |-
                    import { PetSDK } from "petsdk";

                    const petSDK = new PetSDK();

                    async function run() {
                      const result = await petSDK.createPets({
                        id: 596804,
                        name: "<value>",
                      });

                      // Handle the result
                      console.log(result)
                    }

                    run();
                - lang: python
                  label: createPets
                  source: |-
                    import petsdk
                    from petsdk.models import components

                    s = petsdk.PetSDK()

                    res = s.create_pets(request=components.Pet(
                        id=596804,
                        name='<value>',
                    ))

                    if res is not None:
                        # handle response
                        pass
    /pets/{petId}:
        get:
            summary: Info for a specific pet
            operationId: showPetById
            tags:
                - pets
            parameters:
                - name: petId
                  in: path
                  required: true
                  description: The id of the pet to retrieve
                  schema:
                    type: string
            responses:
                '200':
                    description: Expected response to a valid request
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Pet"
                default:
                    description: unexpected error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
            x-codeSamples:
                - lang: go
                  label: showPetById
                  source: |-
                    package main

                    import(
                    	petsdk "petsdk/v2"
                    	"context"
                    	"log"
                    )

                    func main() {
                        s := petsdk.New()


                        var petID string = "<value>"

                        ctx := context.Background()
                        res, err := s.ShowPetByID(ctx, petID)
                        if err != nil {
                            log.Fatal(err)
                        }
                        if res.Pet != nil {
                            // handle response
                        }
                    }
                - lang: typescript
                  label: showPetById
                  source: "import { PetSDK } from \"petsdk\";\n\nconst petSDK = new PetSDK();\n\nasync function run() {\n  const petId = \"<value>\";\n  \n  const result = await petSDK.showPetById(petId);\n\n  // Handle the result\n  console.log(result)\n}\n\nrun();"
                - lang: python
                  label: showPetById
                  source: |-
                    import petsdk

                    s = petsdk.PetSDK()

                    res = s.show_pet_by_id(pet_id='<value>')

                    if res.pet is not None:
                        # handle response
                        pass
components:
    schemas:
        Pet:
            type: object
            required:
                - id
                - name
            properties:
                id:
                    type: integer
                    format: int64
                name:
                    type: string
                tag:
                    type: string
        Pets:
            type: array
            maxItems: 100
            items:
                $ref: "#/components/schemas/Pet"
        Error:
            type: object
            required:
                - code
                - message
            properties:
                code:
                    type: integer
                    format: int32
                message:
                    type: string
