workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    docsSource:
        inputs:
            - location: input.yaml
        overlays:
            - location: https://raw.githubusercontent.com/ryan-timothy-albert/sample-go-sdk/main/codeSamples.yaml
            - location: https://raw.githubusercontent.com/ryan-timothy-albert/sample-typescript-sdk/main/codeSamples.yaml
            - location: https://raw.githubusercontent.com/ryan-timothy-albert/sample-python-sdk/main/py/codeSamples.yaml
              authHeader: authorization
              authSecret: $openapi_doc_auth_token
        output: openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/ryan-local/ryan-local/docs-source
targets: {}
